spring.datasource.url=jdbc:mysql://localhost:30306/usuariosProyecto?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password= abc123.
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
#server.port=8502
#spring.application.name=usuarios
springdoc.api-docs.path=/api-usuarios


#Eureka
eureka.instance.hostname=localhost
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
server.port=8502
spring.application.name=usuarios
eureka.client.service-url-defaultZone=http://localhost:8500/eureka/
eureka.instance.prefer-ip-address=true
